In [11]:
import numpy as np
array1=np.arange(0,21)

array2=np.array([i for i in array1 if i>0 and i%2==0])

array3=np.array([j for j in array1 if j>0 and j%3==0])
print(array1)
print(array2)
print(array3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20]
[ 3  6  9 12 15 18]
