In [14]:
import numpy as np
array=np.arange(30)
array=array.reshape(5,6,order='F')
np.where(array%6==1)

[[ 0  5 10 15 20 25]
 [ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]]


(array([0, 1, 2, 3, 4]), array([5, 0, 1, 2, 3]))